### ISSUE TITLE
adding mean gene conversion rates and tract lengths for the diploid species in the catalog

### ISSUE THREAD

**Issue by fbaumdicker** [popsim-consortium/stdpopsim#1115]
**Currently the diploid species in stdpopsim lack gene conversion parameters**
*The addition of gene conversion will make the simulations more realistic. Gene conversion can break down LD in a different way compared to recombination. As e.g. discussed in this paper https://doi.org/10.1111/mec.13736.*

**Rationale and considerations:**
* Some people argue that gene conversion is initiated more uniformly across the genome than recombination. Others assume that gene conversion is initiated at a rate proportional to the local recombination rate. 
* Currently, msprime only supports a flat mean gene conversion rate along the genome/chromosome. So all we would need to include would be the mean gene conversion initiation rate per generation per base pair and the mean gene conversion tract length, where this length is usually geometrically distributed.
* If only an estimate of the recombination to gene conversion ratio is available we could simply multiple the mean recombination rate with this factor to get a mean gene conversion initiation rate.
* For example, for Drosophila Melanogaster the mean gene conversion tract length is 352 according to this publication:
https://doi.org/10.1093/genetics/137.4.1019*
* @petrelharp mentioned in #1106 that we should also discuss and decide whether using the gc parameters of diploid species should be the default setting or an optional choice.

**Comment by petrelharp** [comment]
I think we'd definitely like to put in estimates for GC rate and tract length for species where that's available! I suppose someone should do it and someone else QC it. As for whether it should be optional or not - it'd help to know how much longer it makes simulations take? Like, how much longer does turning on GC make a simulation of a human chromosome take? (I think this was benchmarked in the msprime paper?)

**Comment by andrewkern** [comment]
> I think we'd definitely like to put in estimates for GC rate and tract length for species where that's available! 

+1

we probably have this for Arabidopsis and Mus as well.

**Comment by jeromekelleher** [comment]
> Like, how much longer does turning on GC make a simulation of a human chromosome take? (I think this was benchmarked in the msprime paper?)

Roughly the same as adding more recombination at that rate, perhaps a little less because GC tends to generate less trapped material.

**Comment by fbaumdicker** [comment]
As GC rates are usually higher than recombination rates, for human population data that would mean we will at least double or triple the time needed in msprime. I guess the time SLiM needs would not change that much.

**Comment by petrelharp** [comment]
We had a lot of discussion in the meeting today about this. The summary is:
- gene conversion would be nice to have on by default as it does affect things
- however, since msprime runtime is quadratic in the number of ancestral chunks, it can affect runtime a *lot* (e.g., if it is 10x recomb rate it can increase runtime by 50x)
- and, gene conversion affects some aspects of genetic diversity but not others
- however, it's essential to have on for bacterial species (since otherwise they'd have no recomb at all)
- it seems confusing to have GC on by default for some species and off by default for others
- we would like to not add more complexity to the API

Notwithstanding the last point, the proposal is:
- insert GC rate/length values into species when known
- but leave GC off by default
- with an easy-to-use flag to turn it on.

We think this sounded acceptible to you, @fbaumdicker? Anyone else have input here? If we go with this we just need a proposal for the design of the flag to turn it on.

**Comment by fbaumdicker** [comment]
Yes, that would be ok for me.
I am not completely sure how most people are actually using stdpopsim and where the best place to turn it on would be. Could the flag be a variable for each contig with a default value set to "off"? I could include such a flag in this PR.
The only thing I know for sure is that the flag should automatically be set if a custom gene conversion rate and length are set.

**Comment by petrelharp** [comment]
I've talked through this with Murillo, here. The options are, I think: (1) make `use_gene_conversion` a property of a Contig; (2) make `use_gene_conversion` an argument to `get_contig`; (3) make `use_gene_conversion` an argument to `simulate()`. In cases (1) and (3) the Contig would have a `gene_conversion_rate` property that might be nonzero but then the simulations would have no gene conversion if it was not turned on.

We think (2) is the way to go - this should be an argument to [`get_contig( )`](https://popsim-consortium.github.io/stdpopsim-docs/latest/api.html#stdpopsim.Species.get_contig). This is because:
- `get_contig( )` is where you can specify the mutation rate and the genetic map, if these are not the defaults
- then gene conversion rate (including "does this contig have gene conversion") is a property of the Contig object, consistent with mutation rate and recombination rate
- it seems less confusing that you wouldn't have a Contig with nonzero GC rate producing sims with no GC.

Ok, if we go with (2) then I think the options are:
- just have a `gene_conversion_rate` argument, that defaults to `0.0`, so then to turn on GC you'd do `contig = species.get_contig("chr2", gene_conversion_rate=species.gene_conversion_rate)`
- in addition (?) have an argument `use_gene_conversion` that defaults to False, and if `True` then uses the species rate.

Same for `tract_length` above, confusingly.

In the command-line API maybe we should *only* add an argument that is `--use-gene-conversion`, a boolean that if passed in uses the species default rate and tract length.

We should remember that our goal isn't to make a fullly-optioned simulator here (that exists already) but rather provide a minimal set of useful defaults easily. However, if it's important for people here to be able to manually set GC rates, well then, we should provide that ability.

**Comment by fbaumdicker** [comment]
I agree, (2) is the best way to handle GC. I would add three optional arguments to `get_contig()`:
`gene_conversion_rate`, defaults to `0.0`
`gene_conversion_tract_length`, defaults to `0.0`
`use_species_gene_conversion`, defaults to False (I really like this option as it would easily enable the most common case)

We need to be clear about how these three interact. The easiest way would be that one has to either define `gene_conversion_rate` and `gene_conversion_tract_length` or `use_species_gene_conversion` but nether both.

But instead of producing an error, we could also handle all cases separately when both are set.

If `use_species_gene_conversion` is True and the species has no GC rates in the catalog this should always be an error.

If `use_species_gene_conversion` is True the species rates are used unless `gene_conversion_rate` and/or `gene_conversion_tract_length` are set manually to something > 0.0. Then we would use the locally set parameter(s) and fill the possibly remaining one with the species default parameters.

If `use_species_gene_conversion` is False and only one of `gene_conversion_rate` and `gene_conversion_tract_length` are set to something > 0.0 we should require the other parameter as well.

I could adapt `get_contig( )` in #1106 accordingly before we merge it?

**Comment by petrelharp** [comment]
Sounds good to me! Except that it's a bit more complicated than we need: I think that if `rate` is provided then `tract_length` should be also - no mixing and matching defaults there. So, the only three valid options would be:
- nothing (default); result is no GC
- `use_species_gene_conversion=True`
- `gene_conversion_rate=x` and `gene_conversion_tract_length=y`

If you'll get to it very soon then I'd say roll it in to #1106; otherwise we should merge that.

**Comment by fbaumdicker** [comment]
Now that #1106 is done we should think about adding more default values for the species that are already in the catalog.

**Comment by petrelharp** [comment]
I believe the topic of this issue (adding gene conversion) has been done, in #1106; in particular one now does
```
contig = species.get_contig(..., use_species_gene_conversion=True)
```
to simulate with gene conversion, if values are provided in the species' contig's definitions.  *Another* issue we might open is "add more GC values to more species" - PRs appreciated!
