### ISSUE TITLE
recapitation fails with new SLiM because of mismatching population names

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/stdpopsim#1140]
Using the development version of SLiM, running the example from the `analysis2/README.md`:
```
import numpy as np
import stdpopsim

species = stdpopsim.get_species("HomSap")

# Adding a specific Distribution of fitness effects
dfe = species.get_dfe("Gamma_K17")

contig = species.get_contig("chr20")
model = species.get_demographic_model("OutOfAfrica_3G09")
samples = model.get_samples(100, 100, 100)  # YRI, CEU, CHB

# Extracting gene annottation
exons = species.get_annotations("ensembl_havana_104_exons")
exon_intervals = exons.get_chromosome_annotations("chr20").astype("int")
contig.add_dfe(intervals=exon_intervals, DFE=dfe)

# Engine used for simulations
engine = stdpopsim.get_engine("slim")

# Simulate
ts = engine.simulate(
    model,
    contig,
    samples,
    seed=236,
    slim_scaling_factor=100,
    slim_burn_in=10,
)
```

... gets the following error:
```
Traceback (most recent call last):
  File "/home/peter/projects/popsim-consortium/analysis2/test.py", line 22, in <module>
    ts = engine.simulate(
  File "/home/peter/.local/lib/python3.9/site-packages/stdpopsim-0.1.3b1-py3.9.egg/stdpopsim/slim_engine.py", line 1281, in simulate
    ts = self._recap_and_rescale(
  File "/home/peter/.local/lib/python3.9/site-packages/stdpopsim-0.1.3b1-py3.9.egg/stdpopsim/slim_engine.py", line 1394, in _recap_and_rescale
    ts = msprime.sim_ancestry(
  File "/home/peter/.local/lib/python3.9/site-packages/msprime/ancestry.py", line 1181, in sim_ancestry
    sim = _parse_sim_ancestry(
  File "/home/peter/.local/lib/python3.9/site-packages/msprime/ancestry.py", line 973, in _parse_sim_ancestry
    raise ValueError(
ValueError: Population names in the input demography and the initial state population table must be equal: pop_0 ≠ p0
```

I'm not clear yet if this is a problem with SLiM, with tskit udpates, or with stdpopsim.

**Comment by mufernando** [comment]
This is definitely on us. Older version of SLiM did not have population names and the new one does. Problem is now the default population name in SLiM is `p0`, `p1` and so on.

In doing the recapitation, we rely on `msprime.Demography.from_old_style` to create the `Demography` object that is used in the recapitation. By default, msprime defines population names as `pop_0`, `pop_1` and so on, which conflicts with the names given by SLiM.

Idk what to do though. Did we update the requirements to use the new SLiM version? Or did this happen just because you had an up-to-date SLiM, @petrelharp?

@grahamgower any ideas? Ideally we should move towards having the SLiM engine dealing with msprime.Demography or demes objects, I think?

**Comment by andrewkern** [comment]
Does it work with the stable slim release?

**Comment by grahamgower** [comment]
The appropriate fix is for us to set the population names in the SLiM code we're generating (so, `p1.name = "foo"`) and make sure we set those names on the demography object that is passed into msprime for recapitation. We'll need to depend on SLiM 3.7 to do the former.

> Does it work with the stable slim release?

Yeah, no problems there.

**Comment by grahamgower** [comment]
Once the names match, there's an additional problem. See https://github.com/tskit-dev/msprime/issues/1947
