### ISSUE TITLE
Neutral proportion should be 0

### ISSUE THREAD

**Issue by xin-huang** [popsim-consortium/stdpopsim#1141]
Hi
I think neutral proportion should be 0 in https://github.com/popsim-consortium/stdpopsim/blob/main/stdpopsim/catalog/HomSap/dfes.py#L83

Because `neutral mutations have 0 proportion because they are not simulated by SLiM`
https://github.com/popsim-consortium/analysis2/commit/4fc99b1dcb638f7d3d8064064360ede354ea83fb#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L31

**Comment by grahamgower** [comment]
Hmm. Did that behaviour get changed recently? Maybe @izabelcavassim, @mufernando or @petrelharp knows?

**Comment by xin-huang** [comment]
I fixed the neutral proportion to 0 https://github.com/xin-huang/stdpopsim/blob/main/stdpopsim/catalog/HomSap/dfes.py#L83
and rerun the DFE pipeline https://github.com/xin-huang/analysis2/blob/dev/benchmark/Snakefile

I got similar results (https://github.com/xin-huang/analysis2/blob/dev/benchmark/plots/chr21/dfe.inference.benchmark.neu.prop.0.pdf) as the ones (https://github.com/xin-huang/analysis2/blob/dev/benchmark/plots/chr21/dfe.inference.benchmark.old.DFE.API.pdf) from the old DFE API.

The results from the new DFE API https://github.com/xin-huang/analysis2/blob/dev/benchmark/plots/chr21/dfe.inference.benchmark.new.DFE.API.pdf

Therefore, I think `stdpopsim` should fix the neutral proportion to 0 when generating the internal `SLiM` script.

**Comment by petrelharp** [comment]
Neutral proportions should not be zero: we changed this when re-working the DFE API after a good deal of discussion. The reason is that whether or not neutral mutations are simulated by SLiM or overlaid afterwards is an implementation detail that should not be visible in the DFE specification.

If you're getting different results, I suspect there's something wrong with your pipeline? (and: Apologies I didn't see this earlier - my github notifications have been overwhelmed; ping on slack if you like?)
