### ISSUE TITLE
don't simulate neutral mutations in SLiM

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/stdpopsim#1149]
@mufernando points out that it looks like we are actually simulating neutral mutations twice, once with SLiM and once with msprime. The fix should be to change [this line](https://github.com/popsim-consortium/stdpopsim/blob/1c489090a6dde9414dc1b8825cdb2d0d540dbe3c/stdpopsim/slim_engine.py#L946) to something like:
```
        mut_props = ", ".join([str(prop) if mt.is_neutral() else 0.0 for prop, mt in d.proportions])
```

We also should have a test that catches this, by doing a SLiM simulation without recapitation and checking if any actual mutations are of the neutral types.

Ah - the test could be added to [this one](https://github.com/popsim-consortium/stdpopsim/blob/1c489090a6dde9414dc1b8825cdb2d0d540dbe3c/tests/test_slim_engine.py#L987), checking that all neutral mutation types have 0.0 proportion. If so, then we could go ahead and recapitate and still run the test.

**Comment by mufernando** [comment]
test that neutral mutations have proportion 0 in SLiM, similar to this: https://github.com/popsim-consortium/stdpopsim/blob/1c489090a6dde9414dc1b8825cdb2d0d540dbe3c/tests/test_slim_engine.py#L987

**Comment by mufernando** [comment]
Peter, it looks like this test you linked is doing the right thing. But none of these tests were being run because we were waiting for SLiM 3.7. See how you were computing the proportion of neutral mutations and excluding them from the mutation rate here: https://github.com/popsim-consortium/stdpopsim/blob/1c489090a6dde9414dc1b8825cdb2d0d540dbe3c/tests/test_slim_engine.py#L997
