### ISSUE TITLE
QC for Chimpanzee (Pan troglodytes)

### ISSUE THREAD

**Issue by xin-huang** [popsim-consortium/stdpopsim#1220]
**PR for new species:** https://github.com/popsim-consortium/stdpopsim/pull/1215

If you volunteer to QC this species, please use the checklist below.
While this list is intended to be comprehensive, it may not be exhaustive.
Where relevant, the QC reviewer should identify that parameter values match
those given in the linked citation(s).

The QC reviewer should start a pull request that fills out the test stubs
with independently obtained values. The reviewer may look at the python code
for rationale provided in comments, but should ignore the actual code
as much as possible - comments in the code should give enough information
that it's obvious how to get the correct value from the provided references.
(In particular, we shouldn't copy-paste the value from the code into the test!)

- [x] Recombination rate.
  - This might be genome-wide, or per-chromosome. Both are fine.
  - Check there's a comment describing where it came from, and/or how calculated.
  - From a publication? Check the value(s) match the publication.
  - Calculated somehow? Average over a recombination map? Redo the calculation.
- [x] Mutation rate.
  - This might be genome-wide, or per-chromosome. Both are fine.
  - Check there's a comment describing where it came from, and/or how calculated.
  - From a publication? Check the value(s) match the publication.
  - Calculated somehow? Redo the calculation.
- [ ] Recombination map (if present).
  - Does it match the assembly? Liftover is fine, if clearly stated.
  - Is the description/long_description a good summary of how the map was created?
- [x] Population size.
- [ ] Generation time.

For each citation, check:
- Doi link.
- Is publication a preprint? Is there a peer-reviewed publication instead?
- Is the year correct.
- Is the author correct (spelling, accents/ligatures/etc.)

Citations are required for:
- [x] Genome reference assembly.
- [x] Mutation rate.
- [x] Recombination rate.
- [ ] Recombination map(s) (if relevant).
- [x] Population size.
- [x] Generation time.

The final PR should:
- [x] fill out the test stubs
- [x] delete the `pytest.mark.skip` lines that make the tests not run
- [ ] make sure they pass, talking to the original author to figure out discrepancies

**Comment by janaobsteter** [comment]
I can take this one!

**Comment by janaobsteter** [comment]
Comments regarding some parameters that might be good to discuss with the authors (I don't know if I got everything right):

1) Population size
The reference for the population size is de Manuel., 2016. They ran a PMSC and MSMC2 analysis to determine the historical effective population size, which suggests a drop in the recent effective population size to something small. However, they've also estimated current Ne through Watterson's theta, which suggests a Ne between 17,000 and 47,000 for specific chimpanzee populations and 74,000 for "All" (Table S2). They do mention a Ne of 15,000, but only as an input parameter for the phasing software.
There is another paper though, Prado-Martinez et al. (doi.org/10.1038/nature12228), that reports Ne of the chimpanzee - although is a bit weird, since they report in 10e-3 units (mistake?)

2) Mutation rate
There is a newer paper, Tatsumoto et al., 2017 (https://www.nature.com/articles/s41598-017-13919-7). It gives a "similar", yet a bit higher, estimate. Don't know if we want to update?

3) Recombination rate
The cited paper, Stevison et al., 2015, reports recombination of 0.8 in units of `4*Ne*r/kB`. They also use Ne estimate of  16,781 and report an "adjusted" rate of 1.193 cM/Mb. In the stdpopsim, the enter Ne value is 15,000, which would lead to 0.8 / (4*15,000) / kB  = 1.33e-8 mutation rate (is this true?). 
Another study (Brandt et al., https://doi.org/10.1073/pnas.2200858119) also used a recombination rate of 1.2 × 10e−8  and cited the same Stevison et al. paper.

**Comment by xin-huang** [comment]
I will discuss those parameters with @kuhlwilm

**Comment by petrelharp** [comment]
Any more info, @xin-huang?

**Comment by xin-huang** [comment]
> Any more info, @xin-huang?

We will discuss it in our group meeting tomorrow, we will let you know after that.

**Comment by kuhlwilm** [comment]
Hi, here some thoughts on these points:

1) Population size: Difficult, but generally de Manuel 2016 is the most complete analysis. If you just want to assign a simple single value as the "average" approximation to each chimpanzee subspecies, use Table S2 from de Manuel, that is the best choice using the most complete data. The more fine-grained SFS-based model (Table S15, S18) uses different 4-population settings with quite different results with bottlenecks, migrations etc. In Kuhlwilm 2019, we used a 3-population model (only central/western chimpanzee + bonobo, no eastern and NigeriaCameroon chimpanzee).
There is no conclusive model for all 4 chimpanzee subspecies, the Brand 2022 parameters are quite a bit off. If "default" should refer to the ancestral Ne, anything around 10k or 15k seems fine, as long as the subspecies-specific Ne is higher. We inferred ancestral chimpanzee at 12,338k (Table S2.3) with the SFS-based model.

2) Mutation rate: The most recent estimate (from 2019) of mutation rate in chimpanzee is: 0.64e-9 per year, which would be 1.6e-8 per generation.
https://www.nature.com/articles/s41559-018-0778-x

3) Recombination rate: If you use the same calculation with Ne of 12,338, you actually arrive at 1.62e-08, which is almost exactly the value from point 2. That doesn't mean I particularly trust these values over slightly different ones (especially since the recombination map is done on one subspecies only), but at least this seems quite coherent here.

**Comment by petrelharp** [comment]
Awesome, thanks @kuhlwilm!

**Comment by petrelharp** [comment]
How does this sound to you, @janaobsteter?

**Comment by janaobsteter** [comment]
Hi! Thanks for the answer! I am just a bit confused since the current
numbers in the catalog (species.py) are
- population size: 15,000
- mutation_rate=1.2e-8
-recombination_rate=0.7e-8

Would it then make sense to replace these with the numbers you are
mentioning above (12,338 for the population size, 1.6e-8 per generation
mutation rate, 1.62e-08 for recombination rate? Sorry, I might have
misunderstood some of it 😅

**Comment by kuhlwilm** [comment]
Hi @janaobsteter,
sorry, I just see there was a misunderstanding in the recombination rate, as mutation rate was also mentioned in the same paragraph above, and then I mixed them up... The recombination rate as calculated above, using the Ne of 12,338, seems too high. Maybe better just take the values from Stevison and that's it: 1.193 cM/Mb.
For mutation rate, there is a clear reference to say 1.6e-08.
For Ne, to be honest any value seems arbitrary. To make it proper with Stevison, it would then be 16,781.
Sorry again for the confusion...

**Comment by janaobsteter** [comment]
Ok, thanks! Now worries, as long as it's clear now :) Then I will create a
PR with these last values that you mentiond here, is this ok?

Thanks again!
Jana

**Comment by kuhlwilm** [comment]
Yes, this makes sense!
Best,
Martin

**Comment by janaobsteter** [comment]
So sorry, I've been away for 14 days (and I thought I've pushed this
already, but apparently not 😥). One question - I can't enter all this new
numbers in the test, but I have changed the species.py file, is this ok?

Best, Jana

**Comment by petrelharp** [comment]
All good! Thanks for coming back to it - we'll get it finished quick. It is okay to change both the species.py file and the tests, since your'e doing it in consultation with others. Go ahead and push, and I'll review it!

**Comment by janaobsteter** [comment]
I've submitted a PR - something is still wrong with the form of it, but I
don't really know how to fix it. But just write in the PR and I can do my
best :)

Jana

**Comment by grahamgower** [comment]
Hey @janaobsteter. The PR looks fine - its just codecov being stupid because you deleted some unused lines of code.

**Comment by petrelharp** [comment]
Awesome! Looks good - I will merge the PR now. Thanks for sticking through, everyone!

**Comment by petrelharp** [comment]
Closed in #1291.

**Comment by petrelharp** [comment]
Whoops - I'd forgotten to actually run the tests, and in fact the generation time isn't matching. Reopening.

**Comment by petrelharp** [comment]
The citation for generation time is [Langergraber](https://www.pnas.org/doi/full/10.1073/pnas.1211740109), which has a pretty clear estimate of 24.6 years for chimps, and this is what @janaobsteter put in the tests. The species definition has 25 years, which I suspect is a rounding of 24.6.
![Screenshot from 2022-06-23 19-19-10](https://user-images.githubusercontent.com/1046249/175449381-2b1c315d-e40c-4dab-b22b-0d4907ba0fdf.png)

I've put in a PR to fix this up - see #1295, but if you (someone?) agrees about 24.6 I'll merge that in and we'll be all good.

**Comment by janaobsteter** [comment]
Hi! Yes, I saw that and that is why I put it in the tests. I also suspect
the rounding, but wasn't sure whether that was "allowed" or agreed upon.

Jana

**Comment by petrelharp** [comment]
Are you happy with this, @xin-huang?

**Comment by xin-huang** [comment]
Yes, looks good to me, thank you @janaobsteter @petrelharp

**Comment by janaobsteter** [comment]
Ok, one last question before I create the PR. I've now set
- mutation_rate=1.6e-8 (they took GI as 24 years, here it says 25, so it's
probably fine?)
- recombination_rate=1.2e-8
- population size: 16781 --> do you want to use the estimate from your
study here? (then just recombination rate needs to change accordingly)

Thanks!
Jana

**Comment by kuhlwilm** [comment]
Hi, and sorry for the slow response!
Generation interval of 25 is indeed due to rounding, and mutation rate is correct.
Recombination rate/Ne: I think it is fine to use the Stevison et al. published values: 1.193 cM/Mb and 16,781
Best,
Martin
