### ISSUE TITLE
QC for Caenorhabditis elegans

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#1226]
**PR for new species:** #904

Further details in issue #834.

If you volunteer to QC this species, please use the checklist below.
While this list is intended to be comprehensive, it may not be exhaustive.
Where relevant, the QC reviewer should identify that parameter values match
those given in the linked citation(s).

The QC reviewer should start a pull request that fills out the test stubs
with independently obtained values. The reviewer may look at the python code
for rationale provided in comments, but should ignore the actual code
as much as possible - comments in the code should give enough information
that it's obvious how to get the correct value from the provided references.
(In particular, we shouldn't copy-paste the value from the code into the test!)

- [ ] Recombination rate.
  - This might be genome-wide, or per-chromosome. Both are fine.
  - Check there's a comment describing where it came from, and/or how calculated.
  - From a publication? Check the value(s) match the publication.
  - Calculated somehow? Average over a recombination map? Redo the calculation.
- [ ] Mutation rate.
  - This might be genome-wide, or per-chromosome. Both are fine.
  - Check there's a comment describing where it came from, and/or how calculated.
  - From a publication? Check the value(s) match the publication.
  - Calculated somehow? Redo the calculation.
- [ ] Recombination map (if present).
  - Does it match the assembly? Liftover is fine, if clearly stated.
  - Is the description/long_description a good summary of how the map was created?
- [ ] Population size.
- [ ] Generation time.

For each citation, check:
- Doi link.
- Is publication a preprint? Is there a peer-reviewed publication instead?
- Is the year correct.
- Is the author correct (spelling, accents/ligatures/etc.)

Citations are required for:
- [ ] Genome reference assembly.
- [ ] Mutation rate.
- [ ] Recombination rate.
- [ ] Recombination map(s) (if relevant).
- [ ] Population size.
- [ ] Generation time.

The final PR should:
- [ ] fill out the test stubs
- [ ] delete the `pytest.mark.skip` lines that make the tests not run
- [ ] make sure they pass, talking to the original author to figure out discrepancies

**Comment by chriscrsmith** [comment]
Hey @attrna ! I have some questions about the citations and values for C. elegans.

- **Generation time**. The number I gleaned from the [citation](https://doi.org/10.7554/eLife.05849") was 3 days: "newly hatched individuals pass through four larval stages (L1, L2, L3, L4) and reach the adult stage after 3 days." It looks like you were going with the 150gens/year = 2.43 days? I thought that value was reported less confidently in the paper. 
- **Recombination rate**. I read in the [citation](https://doi.org/10.1371/journal.pgen.1000419) that each chromosome has a genetic length of 50cM. Shouldn't we use that to calculate rec per chromosome? 
- **Mutation rate**. It looks like the mtDNA mutation rate isn't being implemented. We should specify the mtDNA estimate from the second citation right?
- **Population size**. There were two citations([#1](https://doi.org/10.1016/j.cub.2005.06.022) and [#2](https://doi.org/10.1534/genetics.105.048207)). I was leaning towards the second one, because it's representative of all of Europe? Either way we should choose one of the two, right?

**Comment by petrelharp** [comment]
Closed in #1265
