### ISSUE TITLE
QC for Mus musculus (MusMus)

### ISSUE THREAD

**Issue by nspope** [popsim-consortium/stdpopsim#1439]
**PR for MusMus:** #1437 

If you volunteer to QC this species, please use the checklist below.
While this list is intended to be comprehensive, it may not be exhaustive.
Where relevant, the QC reviewer should identify that parameter values match
those given in the linked citation(s).

The QC reviewer should start a pull request that fills out the test stubs
with independently obtained values. The reviewer may look at the python code
for rationale provided in comments, but should ignore the actual code
as much as possible - comments in the code should give enough information
that it's obvious how to get the correct value from the provided references.
(In particular, we shouldn't copy-paste the value from the code into the test!)

- [ ] Recombination rate.
  - This might be genome-wide, or per-chromosome. Both are fine.
  - Check there's a comment describing where it came from, and/or how calculated.
  - From a publication? Check the value(s) match the publication.
  - Calculated somehow? Average over a recombination map? Redo the calculation.
- [ ] Mutation rate.
  - This might be genome-wide, or per-chromosome. Both are fine.
  - Check there's a comment describing where it came from, and/or how calculated.
  - From a publication? Check the value(s) match the publication.
  - Calculated somehow? Redo the calculation.
- [ ] Recombination map (if present).
  - Does it match the assembly? Liftover is fine, if clearly stated.
  - Is the description/long_description a good summary of how the map was created?
- [ ] Population size.
- [ ] Generation time.

For each citation, check:
- Doi link.
- Is publication a preprint? Is there a peer-reviewed publication instead?
- Is the year correct.
- Is the author correct (spelling, accents/ligatures/etc.)

Citations are required for:
- [ ] Genome reference assembly.
- [ ] Mutation rate.
- [ ] Recombination rate.
- [ ] Recombination map(s) (if relevant).
- [ ] Population size.
- [ ] Generation time.

The final PR should:
- [ ] fill out the test stubs
- [ ] delete the `pytest.mark.skip` lines that make the tests not run
- [ ] make sure they pass, talking to the original author to figure out discrepancies

**Comment by nspope** [comment]
Pinging @igronau

**Comment by igronau** [comment]
I started my review. The species file is missing a citation for the assembly. @peterdfields, Can you add this?

**Comment by peterdfields** [comment]
@igronau This is a tricky one. So the GRCm39 genome doesn't appear to have an associated paper, though the GRCm38 assembly does. I can cite the NCBI information but I'm not sure that fits the format allowed. Can you advise me on what is preferable?

**Comment by igronau** [comment]
I'm pinging @petrelharp about the citation issue for the MusMus assembly. @petrelharp - can you see Peter's question above and advise? This seems like it's going to be a common issue, since not all assemblies are going to be linked to a specific publication. Maybe if the assembly is pulled down from Ensembl, we don't have to require an assembly citation. The genome build is clearly specified in `genome_data.py`.

**Comment by igronau** [comment]
Regarding edits, you should probably do another PR, but maybe wait until I finished my initial review. There are other things I noticed:
1) I tried to recreate the recombination rates from what's written in Cox et al (2009), but couldn't quite figure it out. Can you add a short comment above the `_recombination_rate` object describing how you get these values?
2) Add a short comment above the nuclear mutation rate quoting the statement in the abstract of Uchimra et al (2015) with the mutation rate. This helps track down the value in the pub.
> We estimated the base-substitution mutation rate to be 5.4 x 10−9
(95% confidence interval = 4.6 x 10−9–6.5 x 10−9) per nucleotide per generation in C57BL/6 laboratory mice.

3) Add similar comment for the mitochondrial mutation rate by quoting Goios et al (2007) (or saying you took this from Table 1. Also note that they express the mutation rate per year and not per g, so this should be divided by ypg = 0.75
> we obtained an overall substitution rate for the mouse coding mtDNA of 3.7 × 10−8 substitutions per site per yr.

**Comment by igronau** [comment]
4. Also add explanations for the pop size and average generation time you take from Fujiwara et al. (2022). The generation time they quote is 1 yr and not 0.75. Also, the Ne estimated by MSMC appears to be below 300,000, so a flat value of 500,000 does not quite fit here.

**Comment by petrelharp** [comment]
Well, let's see: our `Citation( )` class requires a DOI, author, and year. Author is "Genome Reference Consortium"; year is fine; but I can't find a DOI. It looks like any URL is okay for the DOI, actually. But, as far as I can tell we don't require (in the code) a citation for the assembly. I think you all can say as well as I whether a citation would be useful here or not? But, if you think it's not necessary, then try leaving it out; if there is an error, then make one with the NCBI url?

**Comment by igronau** [comment]
Thanks, @petrelharp. The assembly citation is not required by the tests. It's required by the QC process, and by the instructions we provide in the development docs. We can relax this to say that if the assembly was downloaded from Ensembl, then a formal citation is not necessary, since the important details of the assembly are well documented in the `genome_data.py` file.

**Comment by nspope** [comment]
I think it's reasonable to include a citation with an URL pointing to the NCBI accession (I guess that'd be https://www.ncbi.nlm.nih.gov/assembly/GCF_000001635.27/ here?)

**Comment by igronau** [comment]
Sounds like a good idea.

**Comment by igronau** [comment]
@peterdfields : I reviewed the new PR #1440 and have a few comments and questions:

1. The citation for **genome assembly** should be moved from the _species object to the _genome object.
2. Your added documentation for the **mutation rates** is great.
3. I still don't get the recombination rates in the model. The way I understand Table 1 of Cox et al. (2009), the average recombination rate for chromosome 1 should be 0.50e-8 = 5.0e-9, and not 2.75e-9. I get the value 0.50e-8 from the table itself (3rd column from left), and also by taking the genetic distance inferred by the revised Shifman approach (96.55 cM) and dividing it by the physical distance between the proximal and distal markers (192.62 Mb = 196.26 Mb - 3.64 Mb). What am I getting wrong here?
5. In your explanation for the **generation time** of 0.75, you say that generation times fall in the range of [1,2], so you select the average value. I think that this should be [0.5,1]. Note that when Phifer-Rixey, et al. (2020) mention the range [1,2] they refer to the **number of generations per year**. I would also not associate Fujiwara et al. (2022) with the generation time because they stick to a generation time of 1.

**Comment by nspope** [comment]
Regarding the per-chromosome recombination rates-- if there's a recombination map for this assembly, then the per-chromosome averages could be calculated from hapmap files using `msprime.RateMap.mean_rate`. Then a note could be added in `species.py` to that effect. 

If the recombination map is going to be added later in another PR, we'd probably do this calculation then anyway. Just a suggestion, in case the Cox et al stuff is hard to resolve.

**Comment by igronau** [comment]
Good point, @nspope. I still think we should be able to get decent chromosome-average rates from Cox et al. (2009).

**Comment by peterdfields** [comment]
@igronau Thank you for your recommendations. Responses to specific queries:

> 1. The citation for genome assembly should be moved from the _species object to the _genome object.

I will move the citation.

> 2. Your added documentation for the mutation rates is great.

Great!

> 3. I still don't get the recombination rates in the model. The way I understand Table 1 of Cox et al. (2009), the average recombination rate for chromosome 1 should be 0.50e-8 = 5.0e-9, and not 2.75e-9. I get the value 0.50e-8 from the table itself (3rd column from left), and also by taking the genetic distance inferred by the revised Shifman approach (96.55 cM) and dividing it by the physical distance between the proximal and distal markers (192.62 Mb = 196.26 Mb - 3.64 Mb). What am I getting wrong here?

I think you're completely right on these estimates. I will update the recombination values as suggested.

> 4. In your explanation for the generation time of 0.75, you say that generation times fall in the range of [1,2], so you select the average value. I think that this should be [0.5,1]. Note that when Phifer-Rixey, et al. (2020) mention the range [1,2] they refer to the number of generations per year. I would also not associate Fujiwara et al. (2022) with the generation time because they stick to a generation time of 1.

I will update the explanation for generation time.

> 5. Regarding Ne, the default value for simulations should be set according to the value that will lead to reasonable values of genetic diversity in the simulated genomes. Does a value of Ne=500,000 have that property? For example, for Homo Sapiens, we set Ne to 10,000, which reflects the "historical average" population size, but not recent population size of any population. What would a reasonable equivalent value be for Mouse?

This is a bit of a tricky one. The 500k number gets brought up in [Booker and Keightley (2018)](https://academic.oup.com/mbe/article/35/12/2971/5123518) (note I was planning on including this work in the DFE parameters) where it is used as part of their SLiM simulations, and they cite a couple earlier studies as the basis for this estimate. Would including this study and the ones they cited as their motivation be sufficient or would additional types of approaches be better?

Thank you again for your suggestions!

**Comment by igronau** [comment]
I think you can use Booker and Keightley (2018) to justify the choice of a long-term Ne of 500,000 for *M. m. castaneus*.  You can cite the older studies if they directly derived this estimate, but if they just use this as an a-priori assumption, then it doesn't help much (it was hard for me to tell if this is the case or not).
From your documentation and the more detailed demographic model inferred by Fujiwara et al. (2022), it seems that *M. m. castaneus* is a bit of an outlier relative to other subspecies of MusMus, due to a dramatic increase in diversity that it experienced ~1,000 years ago. So, the question is whether you want the default Ne for MusMus to reflect this or not.
If your main concern is that you wish to implement a DFE model for *M. m. castaneus*, then maybe the approach should be to first implement a demographic model for it, and this model could better reflect the large Ne.

**Comment by peterdfields** [comment]
> I think you can use Booker and Keightley (2018) to justify the choice of a long-term Ne of 500,000 for M. m. castaneus. You can cite the older studies if they directly derived this estimate, but if they just use this as an a-priori assumption, then it doesn't help much (it was hard for me to tell if this is the case or not).

Okay, great!

> From your documentation and the more detailed demographic model inferred by Fujiwara et al. (2022), it seems that M. m. castaneus is a bit of an outlier relative to other subspecies of MusMus, due to a dramatic increase in diversity that it experienced ~1,000 years ago. So, the question is whether you want the default Ne for MusMus to reflect this or not.

I think this is an issue that I'm not at all sure of and maybe would depend upon the preferences of you and the other members of the stdpopsim team. There might be enough information to generate a least most of the stdpopsim catalog inputs for all three subspecies. Or is there a way to add some sort of flag to specify one or the other subspecies given we're presently mostly working with a single genome reference (this will probably change in the not so distant future)?

> If your main concern is that you wish to implement a DFE model for M. m. castaneus, then maybe the approach should be to first implement a demographic model for it, and this model could better reflect the large Ne.

When you say implement a demographic model, do you mean generate the msprime parameter set for this specific Ne? Or something else? I guess depending upon your reply to the above second point, different implementations might be required.

**Comment by igronau** [comment]
The Ne specified in the species model (the _species object) is a default value used when no additional information is given. My understanding is that if you wish to generate simulated data that fits a specific subspecies, then this should be implemented using  a demographic model. There is no other way to specify alternative values for Ne. In principle, you can have a very simple demographic model for each subspecies with a constant Ne in time, and just specify a value for that Ne that is different than the default value for the species. However, if we go down that road, then I would suggest to implement a  more detailed model for each subspecies with fluctuating Ne in time based on [Fig 3 of Fujiwara et al. (2022)](url). It doesn't look like they have a supp table with values we could directly migrate into a demographic model, but maybe we can ask them?

I guess the simplest thing to do **for now** is to stick with the 500,000 value for Ne and mention that this value reflects the long-term Ne for castaneus. Then you cite Booker and Keightley (2018) or some earlier paper that derived this value directly. You can then add a note saying that there is large variation in Ne among subspecies (cite Fujiwara et al. (2022)), and if one is interested in simulating data for another subspecies, they should implement a demographic model, or at least adjust the Ne to fit the long-term Ne for that subspecies.

**Comment by peterdfields** [comment]
@igronau I have made the suggested changes. I have also requested more details from corresponding author of Fujiwara et al. (2022) so that the values from Fig. 3 might be used in the creation of a demographic model for each of the subspecies. Please let me know if further modifications are required.

**Comment by peterdfields** [comment]
@igronau I have received the MSMC outputs from the authors of Fujiwara et al. (2022) so that they may be used to implement the subspecies' specific demographic models. Once everything is okay with the species submission I can begin this process.

**Comment by igronau** [comment]
That's great, @peterdfields . I will try to have a look at the updates to the species model later this week, while at [ProbGen](https://meetings.cshl.edu/meetings.aspx?meet=PROBGEN&year=23). It'll be great if we can also add detailed demographic models. Should be reasonably straightforward if you have the tables with Ne values.

**Comment by peterdfields** [comment]
Sounds great, @igronau Have fun at the conference!

**Comment by igronau** [comment]
I see that I can't close this. @peterdfields , @nsnope ?
