### ISSUE TITLE
QC for BottleneckMigration_3C07 (OrySat)

### ISSUE THREAD

**Issue by nspope** [popsim-consortium/stdpopsim#1459]
**PR for new model:** #1453
**Original paper:** [Caicedo et al. 2007](https://doi.org/10.1371/journal.pgen.0030163)
**Parameter values:** Table 2 in Caicedo et al 2007, "bottleneck + migration" model
**Population indices:**  0=Oryza rufipogon (wild rice); 1=Oryza sativa indica; 2=Tropical Oryza sativa japonica

**QC'er requests:** Pinging @minesrebollo -- thanks! Please reach out to @igronau or @nspope if you have QC questions.

**Comment by minesrebollo** [comment]
@nspope all the parameters extracted from [Caicedo et al. 2007](https://doi.org/10.1371/journal.pgen.0030163) were checked, do I need to start a pull request for this or that is all?

**Comment by petrelharp** [comment]
Yes, we need a PR to fill out the QC code; see https://popsim-consortium.github.io/stdpopsim-docs/stable/development.html#implementing-tests-for-the-review-of-a-demographic-model for how this works.

**Comment by minesrebollo** [comment]
Hi @ornobalam , I am wondering if the source and destination of these lines are ok:

> msprime.MigrationRateChange(time=0, rate=m_ind_rufi, source=0, dest=1),
> msprime.MigrationRateChange(time=0, rate=m_ind_trj, source=2, dest=1),
> msprime.MigrationRateChange(time=0, rate=m_trj_rufi, source=0, dest=2),
> msprime.MigrationRateChange(time=0, rate=m_trj_ind, source=2, dest=1),
> msprime.MigrationRateChange(time=0, rate=m_rufi_trj, source=2, dest=0),
> msprime.MigrationRateChange(time=0, rate=m_rufi_ind, source=1, dest=0),

If I am interpreting the m rate codification correctly (m_from_to) and population code 0 =rufi, ind = 1, trj =2, shouldn't those lines be:

> msprime.MigrationRateChange(time=0, rate=m_ind_rufi, source=1, dest=0),
> msprime.MigrationRateChange(time=0, rate=m_ind_trj, source=1, dest=2),
> msprime.MigrationRateChange(time=0, rate=m_trj_rufi, source=2, dest=0),
> msprime.MigrationRateChange(time=0, rate=m_trj_ind, source=2, dest=1),
> msprime.MigrationRateChange(time=0, rate=m_rufi_trj, source=0, dest=2),
> msprime.MigrationRateChange(time=0, rate=m_rufi_ind, source=0, dest=1),

?

**Comment by ornobalam** [comment]
Hi @minesrebollo! Thanks for bringing this up because I sometimes struggle with the backwards in time thinking for migration rates. My reasoning was: ind_rufi is the migration rate from indica (1) to rufipogon (0) forward in time. msprime considers the migration rate [backwards in time](https://tskit.dev/msprime/docs/stable/demography.html#sec-demography-direction-of-time), so in the following code:

 msprime.MigrationRateChange(time=0, rate=m_ind_rufi, source=0, dest=1),

Backwards in time, migration is taking place at the rate, m_ind_rufi from 0 (rufipogon) to 1 (indica), but forward in time, it's actually going from indica to rufipogon.

I hope that makes sense! May be helpful to get a second opinion to confirm.

**Comment by minesrebollo** [comment]
Thanks for the clarification @ornobalam , it makes sense!

**Comment by ornobalam** [comment]
Hi @igronau! I agree that the scaling reasoning is a bit clunky here.

About the two strategies for scaling (divergence time = 12,000, ancestral Ne = 150,000), I think they are actually the same. I calculated N_rufi = 12000 / (0.04 * 2)  based on the divergence time.

I wasn't sure if I could use a different mutation rate than the species rate. The paper states the following in the methods about the mutation rate used for the demographic inference:
"The mutation rate, θ, was estimated from the number of synonymous and noncoding segregating SNPs assuming O. rufipogon represented a population of constant size. This assumption is quite reasonable given the excellent concordance between the O. rufipogon and the predictions of the standard neutral model ([Figure 4](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.0030163#pgen-0030163-g004)), and is equivalent to using Watterson's (1975) estimator of θ."

Theta is a scaled mutation rate, so for our mutation rate parameter, we could calculate mu from theta = 4 * Ne * mu. I think they are referring to the theta-W estimate for O. rufipogon (5.42e-3) in Table 1. So, mu = 5.42e-3/(4*150000) = 9.03e-9. Would it make more sense to use this rate for this model?

**Comment by igronau** [comment]
This makes sense now. I'll have a closer look early next week and will let you know if I have additional comments/suggestions about the scaling or mutation rate

**Comment by igronau** [comment]
I had some time to look at this now. The relative scaling of population sizes and times looks fine. However, for clarity, I would specify all values as a function of either T_1 or N_r. Something like:
`T_B = 0.75 T_1`
`N_r = T_1 / (0.04 * 2)`
`N_trj = 0.12 * N_r`
`N_ind = 0.27 * N_r`
`N_B = 0.0055 * N_r`

This way, you only need to fix T_1 and all other parameters are scaled accordingly. If you want T_1 to correspond to 12,000 years, then you should set it to 12,000 / generation_time. I see that generation time is set to 1, so this is okay. However, if someone were to change the assumed generation time, this would also change in the model, so you might want to be careful about this.

Regarding mutation rate, your computations seem well-justified. I would write the expressions as is in the code and use N_r as parameter. Something like:
`Theta_r = 5.42e-3`
`mutation_rate=Theta_r / (4*N_r)`
The only minor question I have here is whether the mutation on synonymous sites (which is what this value captures) also reflects the genome-wide average mutation rate (i.e. in intergenic sites). It's also 3x larger than the mutation rate used for the species (3.2e-9). This is not an issue if all other parameters are scaled appropriately, but it's at least worth noting somewhere.

One final issue I found with the implemented model is with migration rates. In msprime and other simulation programs, migration is specified in rate per generation. From what I understand, Caicedo et al. infer a migration rate of 7 between all pairs of population. However, this migration rate is scaled (upward) by a factor of 2N_r. For example, the expected number of migrants per generation into the rufipogon population is 3.5. This means that the per-generation migration rate is 3.5 / N_r. This same rate should be applied for every pair of populations in the msprime demographic model. This will also mean that the interpretation of directionality doesn't mind, because migration is symmetric in this model.

**Comment by ornobalam** [comment]
Thanks for taking a closer look, and apologies for the delay!

Expressing the parameters in terms of N_r or T_1 makes sense, as does noting that we're using a different mutation rate than the species mutation rate. Should I make those changes and push again?

I did, in a roundabout way, get to symmetric migration between the populations in my model code. From the paper:
"It is important to note that coalescent simulations scale the migration based on population size, so the number of migrants entering into the tropical japonica population is smaller (0.5 × M × νJ = 0.42), than into indica (0.5 × M × νI = 0.945), and O. rufipogon (0.5 × M = 3.5)."

I took these numbers and calculated migration between pairs of populations:
# Migration rates in the form M_from_to, thinking forward in time
    m_trj_rufi = 3.5 / N_rufi
    m_trj_ind = 0.945 / N_ind
    m_rufi_trj = 0.42 / N_trj
    m_rufi_ind = 0.945 / N_ind
    m_ind_rufi = 3.5 / N_rufi
    m_ind_trj = 0.42 / N_trj

All of these come out to the same value of 2.33e-5.

**Comment by igronau** [comment]
Okay, then all is fine. I think it's better to have all parameters expressed as explicit functions of N_r or T_1, but I'll leave it up to you. I just wanted to make sure that nothing got missed anywhere. Is the QC code implemented yet @minesrebollo ?

**Comment by nspope** [comment]
@igronau the QC for this model is in https://github.com/popsim-consortium/stdpopsim/pull/1466

**Comment by ornobalam** [comment]
Hi! I just pushed some of the changes discussed with @igronau (coding in terms of T_1 and N_rufi, using a different mutation rate etc.).

**Comment by nspope** [comment]
Thanks @ornobalam -- could you make a PR with these changes? Please add the commits on an up-to-date feature branch (e.g. update the main branch via git pull and then create a new feature branch).

**Comment by nspope** [comment]
Also, please flag @minesrebollo on that PR as they may need to update the QC accordingly.

**Comment by ornobalam** [comment]
Thanks! I made the PR.

**Comment by igronau** [comment]
I think that if all the QC tests pass, then the PRs can be merged in and the issues closed

**Comment by petrelharp** [comment]
This was done in #1459 (also see #1524).
