### ISSUE TITLE
add lognormal (or at least not gamma) DFE for humans

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/stdpopsim#1470]
Lognormal: Perhaps from Boyko 2008? And/or Huber 2017? (perhaps in the supplement)

Another option would be to do an estimate where a discretized distribution is estimated, as in Kim et al.

**Comment by petrelharp** [comment]
@RyanGutenkunst

**Comment by klohmueller** [comment]
Here are the parameters for a log-normal DFE for humans. This one is for nonsynonymous mutations inferred from the YRI from the 1000 Genomes and comes from Table S3 of Huber et al. (2017).

I would suggest using the “Using recent mutation rate estimates” one which uses a mu=1.5e-8. For this DFE, the mean is -7.37 and the SD is 4.58. 

This can be simulated in R using: rlnorm(100000,-7.37,4.58).

I would also suggest adding a “discrete DFE” as well. We could use one from Table 2 of Kim et al (2017). I will give the parameters here that we inferred from the EUR 1000 Genomes data with mu=1.5e-8. Note,  ranges of |s| correspond to: [0, 10e−5), [10e−5, 10e−4), [10e−4, 10e−3), and [10e−3, 10e−2), respectively. The mass in the [10e−2, 1] range is the complement of the total mass of the four aforementioned categories. We then inferred the proportions of mutations in each bin. We inferred the proportions to be: 0.286, 0.099, 0.222, 0.305.

**Comment by RyanGutenkunst** [comment]
Adding the lognormal was straightforward, since that's built into stdpopsim (but not SLiM). https://github.com/RyanGutenkunst/stdpopsim/commit/1f85624482d47cb02222fe521baac518175309b6 

@petrelharp What's the best way to test this? I recall discussion of functionality for extracting the selection coefficients of newly arising mutations in the simulation. Did that get added? Otherwise, I can fiddle with generating at least a plausible SFS, etc.

**Comment by petrelharp** [comment]
Excellent! It's not our job here to do any testing of the underlying mechanism; here we're just implementing the DFE, and we can assume that the code does what it's supposed to do. If you do think of better unit tests for the underlying mechanism, it'd go in [`tests/test_dfes.py`](https://github.com/popsim-consortium/stdpopsim/blob/main/tests/test_dfes.py). The sort of thing you're suggesting is statistical verification, which wouldn't go in unit tests.

**Comment by petrelharp** [comment]
Otherwise, that commit looks good (but see my comment there) - can you make it a PR?

**Comment by RyanGutenkunst** [comment]
> I would also suggest adding a “discrete DFE” as well. We could use one from Table 2 of Kim et al (2017). I will give the parameters here that we inferred from the EUR 1000 Genomes data with mu=1.5e-8. Note, ranges of |s| correspond to: [0, 10e−5), [10e−5, 10e−4), [10e−4, 10e−3), and [10e−3, 10e−2), respectively. The mass in the [10e−2, 1] range is the complement of the total mass of the four aforementioned categories. We then inferred the proportions of mutations in each bin. We inferred the proportions to be: 0.286, 0.099, 0.222, 0.305.

I think will require a small update to the stdpopsim DFE code to enable this sort of DFE. So it should probably go in its own issue. A statistical detail (since I always get concerned about pdfs on the log scale)... For this parameterization, 0.088 weight is for the [1e-2, 1] range. Is that uniform on the linear scale or the log scale? In other words, is half the mass assumed to reside between [1e-2, 0.505] or between [1e-2, 1e-1]?

**Comment by petrelharp** [comment]
We've added the lognormal in #1480, so perhaps we can close this? And open another issue for the discrete DFE that clarifies @RyanGutenkunst 's question about it in the previous comment?
