### ISSUE TITLE
add 'best' DFE from Kyriazis et al

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/stdpopsim#1494]
The paper https://www.biorxiv.org/content/10.1101/2022.08.12.503792v1 presents a "best" DFE they recommend using for a variety of other species. This is a DFE estimated from humans. We should put this one in!

**Comment by petrelharp** [comment]
From the meeting: Should this be a "generic" DFE or under HomSap? (ping @ckyriazis?)

**Comment by ckyriazis** [comment]
the way we present it in our paper is that it could be used as a "generic DFE" for species that dont have a DFE (since some evidence suggests that the DFE doesnt vary a ton, at least across mammals) but in reality it is pretty much a human DFE estimated from human data. so my vote would be to add it to HomSap

**Comment by petrelharp** [comment]
This was done in #1505.
