### ISSUE TITLE
Implement key-value pairs for specifying sampling

### ISSUE THREAD

**Issue by ndukler** [popsim-consortium/stdpopsim#203]

**Comment by andrewkern** [comment]
Noah I'm going to assign you to this. 

One thought-- it might be convenient to offer the use the possibility of setting the key-value pairs for sampling from a file. Maybe json format would be fine here?

**Comment by jeromekelleher** [comment]
We can add in a dictionary mapping the population names to the number of samples. This could be done using kwargs in the ``get_samples`` method probably.

I think we should focus on other stuff for now though: this is not a vital feature for the first release. The most important thing is to get the names/ids of things nailed down in a forward compatible manner.

**Comment by jeromekelleher** [comment]
We can update to using something more like the msprime 1.0 sampling APIs. One thing we could do is to check if the first argument to ``get_samples`` is a dictionary, and then use this mapping like we do in msprime.

A question here is whether we should keep our dependency on msprime objects for sampling? Currently we return a list of msprime.SampleSet (well, after #764). Should we return a stdpopsim.SampleSet so that we're not using msprime objects? (See also #320)

**Comment by nspope** [comment]
This was done in #1361, closing
