### ISSUE TITLE
CLI --help-genetic-maps README ref

### ISSUE THREAD

**Issue by agladstein** [popsim-consortium/stdpopsim#208]
currently the `stdpopsim homsap --help-genetic-maps` says "Please see the README for more details."
What README is that talking about? I assume that should just say Read The Docs.

**Comment by jeromekelleher** [comment]
This is referring back to the README that's in the genetic map tarball. Probably this should be taken out of the description text and put into a comment. Either that or we make a link to the README on the webserver where we're hosting the tarball (but we'd have to pull the README out of the tarball).

Any thoughts @andrewkern?

**Comment by gtsambos** [comment]
Adding this to #208

**Comment by gtsambos** [comment]
(Sub-issue for #215)

**Comment by agladstein** [comment]
Could we add a link to the README?

Now it says:
```
This genetic map is from the Phase II Hapmap project and based on
    3.1 million genotyped SNPs from 270 individuals across four
    populations (YRI, CEU, CHB and JPT). Genome wide recombination
    rates were estimated using LDHat. This version of the HapMap
    genetic map was lifted over to GRCh37 (and adjusted in regions
    where the genome assembly had rearranged) for use in the 1000
    Genomes project. Please see the README file on the 1000 Genomes
    download site for details of these adjustments.
```

**Comment by dschride** [comment]
I remember when 3.1 million SNPs was A LOT of SNPs.

**Comment by jeromekelleher** [comment]
The issue is that the text needs to make sense both in HTML and on the terminal command line @agladstein, so embedding links doesn't work. I don't think there's any point in putting in hyperlinks into the help text output, as it breaks the text layout and they're rarely clickable anyway.

The right solution is to make it so we can have restructured text in the ``description`` fields which gets  parsed and rendered correctly in both text and HTML. I think I can see how to do this but it'll be tricky to get working.

But for now, we only have plain text as the lowest common denominator, and so we can't have hyperlinks.

**Comment by agladstein** [comment]
makes sense.
