### ISSUE TITLE
Make it clear that random seeds are available in Python API

### ISSUE THREAD

**Issue by gtsambos** [popsim-consortium/stdpopsim#361]
Can you specify a random seed for simulations that are run with the Python API?

If not, we should add this!!
If so, we should document it better.

**Comment by gtsambos** [comment]
okay, after some digging, I can see that we can do this (at least, for the default msprime engine) by passing a `seed` option into the `simulate` method. 

At present, it isn't showing up in the displayed API because it isn't an attribute of the overarching `Engine` superclass, but an attribute of the individual engines (eg. `_Msprime`). Is there perhaps an argument that this *should* be an attribute of the superclass? Since SLiM also allows you to set a seed. (I imagine we'd want this for any future simulation engine, also).

The other option is to explicitly display these engines in the API by removing the `_`, but I'm guessing there was some reason for this (@grahamgower ?)

Broader issue here is that from the API, it looks like the feature set of the Python interface is more limited than it actually is, which might stop people from using it

**Comment by grahamgower** [comment]
Good point @gtsambos . Certainly there's an argument for making `seed` a fixed parameter by including it in the superclass, but I don't think its necessary to make that decision yet. I think the easiest way forward here is as you suggest: remove the `_` and add some docstrings for each engine's `simulate()` method. There will always be engine specific parameters - e.g. it shouldn't take much effort to add keyword args for `num_replicates`, `record_full_arg`, etc. For msprime, its pretty easy to bypass the stdpopsim API right now, so this stuff probably isn't high priority.

I think my original motivation for having the underscore was just so that people use the engine specific classes via `get_engine()`, rather than instantiating their own. This follows the rest of the stdpopsim API for things like species and models.
