### ISSUE TITLE
exporting to vcf

### ISSUE THREAD

**Issue by juanjo75es** [popsim-consortium/stdpopsim#362]
I am trying to convert a simulation to fasta files. First I export the result to vcf, then I try to manipulate it with bcftools but it seems there is version compatibility problem.
If I run that:
`bcftools call -m -O z foo2.vcf > foo2.2.vcf.gz`
I get this error:

> Note: none of --samples-file, --ploidy or --ploidy-file given, assuming all sites are diploid
> Wrong number of PL fields? nals=2 npl=-1

And if I run that
`vcfutils.pl vcf2fq foo2.vcf > foo2.fq`
I get

> substr outside of string at /usr/bin/vcfutils.pl line 557, <> line 141887.
> Use of uninitialized value in lc at /usr/bin/vcfutils.pl line 557, <> line 141887.
> substr outside of string at /usr/bin/vcfutils.pl line 557, <> line 141887.

I wonder if that is an issue or I am doing something wrong.

**Comment by gtsambos** [comment]
Hi @juanjo75es, I think this is probably an issue for [tskit](https://github.com/tskit-dev/tskit) rather than for stdpopsim -- when you converted the tree sequence file to a vcf, did you use the `write_vcf` method (documented [here](https://tskit.readthedocs.io/en/latest/python-api.html#tskit.TreeSequence.write_vcf))? If so, did you run it with any of the extra arguments? Did you specify a  `ploidy` value? (If you didn't, the default value is a ploidy of 1, which doesn't look right for this particular application)

> Note: none of --samples-file, --ploidy or --ploidy-file given, assuming all sites are diploid
Wrong number of PL fields? nals=2 npl=-1

You will have to create these files yourself using the information in the tree sequences. If this is your first time using tree sequences, I'd suggest you have a skim through tskit's [documentation](https://tskit.readthedocs.io/en/latest/index.html) if you haven't already -- there's lots of useful info about how to get info about the sample IDs out etc ✨

**Comment by juanjo75es** [comment]
Hi @gtsambos, I used the command line:
`tskit vcf foo2.ts > foo2.vcf`
I see now it's not related with stdpopsim...
Thanks, I will look into the documentation of tskit.
