### ISSUE TITLE
Write tutorials for a "pre-existing model" and the SLiM engine

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/stdpopsim#458]
I'm on this, and doing a general pass through the tutorial: will post a PR later today. I hope no-one else is working on this at the same time, except maybe #340?

**Comment by grahamgower** [comment]
I had a couple of thoughts that I wanted to mention here...
 * Using `-vv` on the CLI will increase verbosity to level 2, triggering the slim script to print out each registered event. This might be useful to users when scaling, to confirm that the coarsness of the simulation is not obviously crazy. Perhaps unintuitively, `-vv` can be combined with `--quiet`.
* When I started writing the slim engine, I'd imagined that advanced users might want to print out the slim script with `--slim-script`, and make some customisations before running it with slim manually. It turns out the post-slim recap bits can be quite subtle to get right and this process will be difficult for users in practice. If you have any thoughts about how/whether this sort of thing could/should be made easier, I'd love to hear them.

**Comment by petrelharp** [comment]
Ah, I haven't paid attention to the CLI portion of the tutorial. I'll have a go at a SLiM/CLI portion next.

> It turns out the post-slim recap bits can be quite subtle to get right and this process will be difficult for users in practice.

What are the biggest gotchas? I was imagining that people would have to read the pyslim documentation (which I recently improved, and should link to here), but if there's only one population you're trying to recapitate it's pretty straight forward, I thought?

**Comment by grahamgower** [comment]
Two additional things come to mind:
 * It requires non-standard simplification. To permit temporal sampling of individuals, I chose to make all sampling done by "remembering" individuals.
 * Node times need to be scaled to match the value of Q within the SLiMulation, so that the pre- and post- recapitation parts of the trees have the same units of time.

**Comment by petrelharp** [comment]
> It requires non-standard simplification. 

That seems like the right use of "remembering"!  Well, just plain simplify won't get rid of any remembered individuals, at least, and the [`simplify_remembered`](https://github.com/popsim-consortium/stdpopsim/blob/ba517491e341fb307d423a8ecdbae0ca33c22ad7/stdpopsim/slim_engine.py#L533) would be easy enough to put in an example somewhere.

> Node times need to be scaled to match the value of Q

Oh, right. That is trickier. Maybe we can expose [the relevant code](https://github.com/popsim-consortium/stdpopsim/blob/ba517491e341fb307d423a8ecdbae0ca33c22ad7/stdpopsim/slim_engine.py#L642) as another function, to make this easier for people? Like `slim_engine.rescale_slim_times( )`?

**Comment by grahamgower** [comment]
Yeah, exposing some post-slim helper function(s) is definitely a good idea. Maybe there could be something like a `_SLiMEngine.recap_factory()` that takes the same args as `simulate()`, but returns a function that can be called on a tree sequence to do all the necessary post-SLiM bits?

**Comment by petrelharp** [comment]
Or, just a single function `.recapitate_and_rescale( )`?

**Comment by petrelharp** [comment]
After we do this we should update the tutorial to give an example of how to do this.

**Comment by grahamgower** [comment]
I think #460 and #465 have covered this. Can it be closed?
