### ISSUE TITLE
questions on adding new model

### ISSUE THREAD

**Issue by agladstein** [popsim-consortium/stdpopsim#491]
Partly because I want to check that the adding new model docs make sense, and partly because I want to add a model, I'm trying to add a model.

One thing that I'm confused about is once I've written a demographic model function, how is it incorporated into `stdpopsim`?  Do I need to build something or??

I've added a function to the `stdpopsim/catalog/homo_sapiens.py`, but the new model I've added doesn't show up in `demographic_models`.

```
import stdpopsim
species = stdpopsim.get_species("HomSap")
contig = species.get_contig("chr22")
for x in species.demographic_models:
   print(x.id)
   
OutOfAfrica_3G09
OutOfAfrica_2T12
Africa_1T12
AmericanAdmixture_4B11
OutOfAfricaArchaicAdmixture_5R19
Zigzag_1S14
AncientEurasia_9K19
PapuansOutOfAfrica_10J19
```

**Comment by agladstein** [comment]
I also don't understand how to write the unit test. Where does it go? What does it entail?

**Comment by grahamgower** [comment]
> One thing that I'm confused about is once I've written a demographic model function, how is it incorporated into `stdpopsim`? Do I need to build something or??

After defining your model function, there needs to be a call like `_species.add_demographic_model(_your_model_func_here())`. This registers your model in the catalog for the `_species` defined in that catalog file. The `_species` is defined towards the top of the file. In case you've already done this, and it's still not showing up, then maybe it's easiest if you just open a PR with your current changes so we can see what's gone wrong.

To give a concrete example, the last model entry in `stdpopsim/catalog/homo_sapiens.py` looks like this (ellipses inserted here for brevity).
```
def _papuans_10j19():
    id = "PapuansOutOfAfrica_10J19"
    ...
    return stdpopsim.DemographicModel(...)

_species.add_demographic_model(_papuans_10j19())
```

> I also don't understand how to write the unit test. Where does it go? What does it entail?

All of the unit tests go under the `tests/` folder. There should be a `tests/test_*.py` file for each species in the catalog. So if your model is for homo sapiens, then the unit test should go in `tests/test_homo_sapiens.py`. You'll see at the bottom of that file is a list of (very short) classes, with one for each HomSap model in the catalog. There are currently two types of models in the file, corresponding to models that have been QCed, and models that haven't (note, all current models should have been QCed, I'll open a separate issue about this!). QCed models inherit from `test_models.QcdCatalogDemographicModelTestMixin` and non-QCed models inherit from `test_models.CatalogDemographicModelTestMixin`. E.g.

```
class TestJacobsPapuansOutOfAfrica(
        unittest.TestCase, test_models.QcdCatalogDemographicModelTestMixin):
    model = species.get_demographic_model("PapuansOutOfAfrica_10J19")
    qc_model = homo_sapiens_qc.DenisovanAncestryInPapuans()

# Models that have not been QC'd:

class TestGutenkunstThreePopOutOfAfrica(
        unittest.TestCase, test_models.CatalogDemographicModelTestMixin):
    model = species.get_demographic_model("OutOfAfrica_3G09")
```

You should add a new class for your model, using the OutOfAfrica_3G09 one above as an example. As part of the model QC process, it will get modified to match the QCed model classes.

Actually, it should be possible to automate the unit test process so that this step isn't necessary when adding new models, but no one has written the code for this yet (see #305). But I expect that this part of the process will be deprecated soon.

**Comment by agladstein** [comment]
I added a draft PR. Can you take a look and let me know what I'm missing?

**Comment by grahamgower** [comment]
> I've added a function to the `stdpopsim/catalog/homo_sapiens.py`, but the new model I've added doesn't show up in `demographic_models`.
> 
> ```
> import stdpopsim
> species = stdpopsim.get_species("HomSap")
> contig = species.get_contig("chr22")
> for x in species.demographic_models:
>    print(x.id)
>    
> OutOfAfrica_3G09
> OutOfAfrica_2T12
> Africa_1T12
> AmericanAdmixture_4B11
> OutOfAfricaArchaicAdmixture_5R19
> Zigzag_1S14
> AncientEurasia_9K19
> PapuansOutOfAfrica_10J19
> ```

Another thing that could cause this, is if the changes aren't propagated to where `import stdpopsim` is importing from. E.g. you have stdpopsim installed via pip, so that gets imported rather than the stdpopsim in your cloned git repository. The dev docs suggest using a virtual environment. https://stdpopsim.readthedocs.io/en/latest/development.html#using-a-virtual-environment

Maybe you can check which location your stdpopsim import corresponds to?
```
$ python
Python 3.8.2 (default, Apr  8 2020, 14:31:25)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import stdpopsim
>>> stdpopsim.__version__
'0.1.1.dev21+ng5f90c82.d20200214'
>>> stdpopsim.__file__
'/home/grg/src/stdpopsim/stdpopsim/__init__.py'
```

Personally, I find virtual environments to be very awkward for development, and always use a different approach. On my workstation, I don't have conda things, just pip packages. And then in the cloned stdpopsim folder I run `python setup.py develop --user`, which links that folder into python's import paths. It's important that you only have one installation of the package at a time though, so its worth checking/removing others with:
```
$ pip uninstall stdpopsim  # remove --user pip packages
WARNING: Skipping stdpopsim as it is not installed.
t490:stdpopsim $ sudo pip uninstall stdpopsim  # remove system-wide pip packages
WARNING: Skipping stdpopsim as it is not installed.
```
Before you do
```
$ cd ~/src/stdpopsim
$ python setup.py develop --user
...
$ pip list | grep stdpopsim
stdpopsim                     0.1.2.dev105+ngbe5bd2c /home/grg/src/stdpopsim
``
Note that the "activate" branch of your repository will be the one that takes effect, so when you switch branches that will change what you get via 'import'. So I guess this approach can lead to confusion, if you don't know or forgot how things were set up.

**Comment by agladstein** [comment]
Okay, I was already in a virtual environment that I had made following the [docs](https://stdpopsim.readthedocs.io/en/latest/development.html#using-a-virtual-environment), but I guess I needed to install it again after making changes. I just did
```
python3 -m pip install -r requirements/development.txt
```
and now it works.

So, does that sound right? In order to get imports to work from any changes to functions/modules you need to install in the dev environment again?

**Comment by grahamgower** [comment]
Doesn't that just install the dependencies, not the (stdpopsim) package itself? I don't do dev work in a virtual environment, so really don't really know what's going on here. But if it works now, great!

**Comment by agladstein** [comment]
> Doesn't that just install the dependencies, not the (stdpopsim) package itself?
I have no idea... but those virtual env instructions don't say anything else about installing stdpopsim package... so, it must?

Does anyone else know? @jeromekelleher @apragsdale @petrelharp 
This should be a reproducible process. I think we can assume that people submitting models aren't going to be pip/python packaging experts.

**Comment by petrelharp** [comment]
I am not (yet?) a virtual environment person either. @jradrion?

**Comment by jradrion** [comment]
I would think you'd need to reinstall `stdpopsim` via either `python setup.py install` or `python setup.py develop --user` in your cloned directory to get your changes to work regardless of whether you are using a virtual environment or not. If you had previously installed `stdpopsim` via pip you might want to uninstall via pip first.

`python3 -m pip install -r requirements/development.txt`
should only be installing the packages listed in `development.txt`, not `stdpopsim`, no?

**Comment by agladstein** [comment]
At least in the virtual environment, I think that you do not need to do `python setup.py install` or `python setup.py develop --user` to get your changes to work. It should happen automatically because in the dev environment, you should just be using the source code directly not a package.

I think my environment was messed up because I had previous installed `stdpopsim`. Deleting the virtual env and just following the instructions on the RTD worked for me.
So, I think using the virtual env following the instructions on RTD should "always" work, as long as you do not also `python setup.py install`, and if you do, you'll have to uninstall it.
To get the CLI to work - `python3 -m pip install -e .` works, and I don't think once you do that, you don't need to install again to get it to work after changes.

But, correct me if I'm wrong.

**Comment by grahamgower** [comment]
Also beware that the current working directory will be in the Python import path. So if you open an interactive python session (or run a script) while in the top-level folder of the cloned repository, then the you'll import the package from your currently checked out branch. Whenever I have any uncertainty, I find the easiest thing to do is check the location of the import'd package in an interactive session (e.g. `import stdpopsim` followed by `stdpopsim.__file__`).
