### ISSUE TITLE
Tests no longer pass with msprime update

### ISSUE THREAD

**Issue by apragsdale** [popsim-consortium/stdpopsim#518]
There was a recent change (this week) to msprime dev branch that removes an argument to `get_ll_representation` (this commit: https://github.com/tskit-dev/msprime/commit/cd522e3361d21a93d7ed6c8323a8dbb065630481#diff-3af8c5bda4976d0bd25e9e5754497a74). This now breaks the tests, so that all model equivalency tests fail with `TypeError: get_ll_representation() takes 1 positional argument but 2 were given` if you have the up to date msprime dev branch installed.

This is a pretty straightforward fix, but I guess this highlights the overall fragility of the stdpopsim resource as a whole which relies on other software that is also continuously developed. If a simulation backend changes, which they are bound to do, that could leave us with a stdpopsim that cannot run some of the unit tests, like here, or doesn't work at all. Or that it works with one release of msprime, but not a later one.

Is this an issue that has been generally discussed, with steps we take to make sure that stdpopsim still works as backends are updated and changed?

**Comment by petrelharp** [comment]
Recording somehow which version(s) of software this works with should do it?

**Comment by apragsdale** [comment]
I guess more generally (for example when msprime 1.0 is released), do we just wait to see what breaks and fix it then? Just wondering if there is a plan in place to stay on top of updates.

**Comment by grahamgower** [comment]
We'll likely move to depending on `msprime >= 1.0` shortly after 1.0 is released, because there are some new features that we want to make use of (notably to resolve issues #260, #401, and #441). The simplest scenario is that stdpopsim releases before msprime 1.0 is released will only require msprime 0.7.4, and stdpopsim releases afterwards will require msprime 1.0.

I think we should make a best effort now to be forwards compatible with the next msprime release. It's plausible there will be more issues like this, as breaking changes are being introduced in the lead up to msprime 1.0. But given that we'll likely release a new stdpopsim before msprime 1.0, this might become incompatible with msprime 1.0 anyway. If that happens, we can make a "stable branch" for stdpopsim and apply small msprime-1.0 compatibility fixes and release new stdpopsim versions off that branch. We needn't worry about this unless/until the need arises though.

Right now, we probably need to do what @petrelharp suggests, and have some version specific code. If that ends up being the case, then we should open a new issue to track the removal of that code for post-msprime-1.0. In any event, I'll take a look and rummage up a PR for the current issue.

**Comment by jeromekelleher** [comment]
I hadn't realised that stdpopsim was using these internal msprime APIs. Hmm.

**Comment by jeromekelleher** [comment]
Great catch @apragsdale, I think it's probably simplest to change this on the msprime side. I forgot that we were using these msprime APIs here when I was refactoring.

**Comment by petrelharp** [comment]
> I hadn't realised that stdpopsim was using these internal msprime APIs. Hmm.

If they're internal (which is what I thought?) then we shouldn't be using them?

**Comment by jeromekelleher** [comment]
> If they're internal (which is what I thought?) then we shouldn't be using them?

We're using them for the tricky problem of comparing models to each other, which is core functionality for QC. Probably this should be brought into msprime, removing the need to write this trick code in stdpopsim (and hence having to much about with low-level stuff like this).

**Comment by jeromekelleher** [comment]
Reverted the change to msprime in https://github.com/tskit-dev/msprime/pull/1038

See https://github.com/tskit-dev/msprime/issues/1036 and https://github.com/tskit-dev/msprime/issues/1037 for longer term plan.
