### ISSUE TITLE
QC for PonAbe

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#544]
The **PonAbe** species definition has not yet been QCed!

If you volunteer to QC this species, please use the checklist below.
While this list is intended to be comprehensive, it may not be exhaustive.
Where relevant, the QC reviewer should identify that parameter values match
those given in the linked citation(s).

- [ ] Recombination rate.
  - This might be genome-wide, or per-chromosome. Both are fine.
  - Check there's a comment describing where it came from, and/or how calculated.
  - From a publication? Check the value(s) match the publication.
  - Calculated somehow? Average over a recombination map? Redo the calculation.
- [ ] Mutation rate.
  - This might be genome-wide, or per-chromosome. Both are fine.
  - Check there's a comment describing where it came from, and/or how calculated.
  - From a publication? Check the value(s) match the publication.
  - Calculated somehow? Redo the calculation.
- [ ] Recombination map (if present).
  - Does it match the assembly? Liftover is fine, if clearly stated.
  - Is the description/long_description a good summary of how the map was created?
- [x] Population size.
- [ ] Generation time.

For each citation, check:
- Doi link.
- Is publication a preprint? Is there a peer-reviewed publication instead?
- Is the year correct.
- Is the author correct (spelling, accents/ligatures/etc.)

Citations are required for:
- [ ] Genome reference assembly.
- [x] Mutation rate.
- [x] Recombination rate.
- [ ] Recombination map(s) (if relevant).
- [x] Population size.
- [ ] Generation time.

**Comment by grahamgower** [comment]
Some notes on the PonAbe parameters:
 * Nater et al. 2017 use mu=1.5e-8 (hoping that the value is similar to humans and chimps) and 25 year generations (citing [this book](https://oxford.universitypressscholarship.com/view/10.1093/acprof:oso/9780199213276.001.0001/acprof-9780199213276)).
 * Locke et al. 2011 assumed a mutation rate of 2.0e-8 and 20 years per generation, both without citation.

The current stdpopsim code uses mu=1.5e-8 and 20 years per generation, and the only demographic model implemented is from Locke et al.. Probably it would be better if we were more consistent here. Thoughs @apragsdale?

Ensembl only include an old assembly, btw. http://rest.ensembl.org/info/assembly/Pongo%20abelii
This has assembly name `PPYG2` (possibly why stdpopsim included the wrong name), and no accession information. But there appear to be three assemblies (https://www.ncbi.nlm.nih.gov/assembly/organism/9601/latest/) and the PPYG2 lengths match the 2008 ponAbe2 assembly.

**Comment by apragsdale** [comment]
Right, if I can remember back why I made those choices... I think I stuck with the Nater et al 2017 mutation rate because that is what they used when inferring the recombination maps that we have. And for the same reason we're using 2008 ponAbe2, since the recombination map matches that assembly.

I used the Locke et al generation time assumption because we need to convert physical units back to units of generation time for the simulation, and since they used a 20 year generation time to convert to genetic to physical units to begin with, it's most consistent to use that same value to convert back for our simulations.

It might make sense to also use a mutation rate of 2e-8 to match Locke et al. Although I think there is going to be that tension in all the species (it's come up with Dmel and humans before, I remember) - since we're pulling from multiple sources to compile genome and population parameters, they will clash because all the different sources use different assumed values, and you're pretty much guaranteed to have contradictions as you try to make them all fit together.

**Comment by petrelharp** [comment]
Just checking @grahamgower - do you want to work on this or get someone else to finish it off?

**Comment by grahamgower** [comment]
I can take another look.

**Comment by petrelharp** [comment]
Ping @grahamgower - shall I get someone else to do this?

**Comment by grahamgower** [comment]
I'm still plugging away at this, but have been slowed by yet more minor annoyances during the liftover (chromosome names changed: chr2a->chr2A and chr2b->chr2B, which broke the maintenance script).
