### ISSUE TITLE
selection: introduce drawn mutation with a specific frequency

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#586]
This should be a fairly straightforward change. (1) add an allele frequency field (e.g. `initial_af`) to the `stdpopsim.ext.DrawMutation` class, (2) hook this into `slim_engine.py` so the `drawn_mutations` array in the slim script is populated with this new field, (3) change the `add_mut()` function in the slim script to sample the appropriate number of chromosomes.

**Comment by dschride** [comment]
Ideally the individuals chosen to receive this mutation should be consistent with the tree at that site, no? I.e. there should be some internal branch ancestral to that set of chromosomes and that set alone. Otherwise we have a mutation that had to have recurred (perhaps up to k times if k is the initial frequency).

**Comment by grahamgower** [comment]
Yes, you're absolutely right, this is a bad idea. Closing. :)

**Comment by dschride** [comment]
Run away! Run away!
