### ISSUE TITLE
support more complex DFEs with the slim engine

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#588]
#462 added the ability to simulate a distribution of fitness effects (DFE), but in a very simple/restrictive way. After #587 is done, the DFE will also be able to apply to specific genomic regions. One additional feature we might like, is to be able to specify that the dominance coefficient for new mutations is a function of the selection coefficient. For example, Kim et al. 2018 [1] simulated a DFE with a gamma distribution (which #462 enables) and a dominance of `h(s) = 0.5/(1–7071.07s)` (which is not enabled by #462).

This can be done using SLiM's `fitness()` callbacks. But it's not clear how we would permit arbitrary dominance calculations from the Python API. Perhaps we could accept an string of eidos code to be used in a `fitness()` callback (but this seems hacky and error prone)?

[1] https://doi.org/10.1371/journal.pgen.1007741 (see pg. 23)

**Comment by petrelharp** [comment]
I'm not enthusiastic about the `fitness( )` callback method, since it's fairly slow. But, maybe this is getting ahead of ourselves, since there's no published s-h relationship (according to Kirk, the above is speculative)?

**Comment by grahamgower** [comment]
Agreed. The discussion on the popsim call indicated that we probably don't need to worry about this kind of model generality, as in most cases additive dominance is assumed. In a pinch, multiple mutation types can be used to model a mixture of different dominance coefficients (although not dependent on the value of `s`).

I'm going to close this issue. If someone really thinks it would be a useful addition, we can reopen.

**Comment by ckyriazis** [comment]
just wanted to chime on on this in case this is something we want to revisit in the future. I've made some attempts at implementing an h-s relationship in slim (initially following the approach from Kim 2018) and did indeed find that the fitness() callback method was quite slow - enough so that it made my simulations intractable. 

recently, however, i was revisiting this issue and asked Ben for some input, and he had a few ideas that he outlined [here](https://groups.google.com/g/slim-discuss/c/ALnZrzIroKY/m/oe9alJ7VAQAJ). the last option seems pretty useful and will be added to future versions of the slim manual.

**Comment by petrelharp** [comment]
For future reference, here's the bit of the manual (from Ben):
[SLiM_Manual_domcoeff.pdf](https://github.com/popsim-consortium/stdpopsim/files/5307081/SLiM_Manual_domcoeff.pdf)
