### ISSUE TITLE
streamline CI for PRs

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/stdpopsim#638]
In #632, @hyanwong ran across a number of inscrutible problems when simply submitting a PR to fix up some documentation. We should make this easier, and document what needs to happen. Maybe @platipo has some insight (in particular, why @hyanwong needed to enable orbs on *his* circleCI account)?

**Comment by hyanwong** [comment]
Or, indeed, why I would want my own circleCI account in the first place.

**Comment by petrelharp** [comment]
Yeah - I think that we'd like it if you *don't* need a circleCI account.

**Comment by hyanwong** [comment]
I have a dim recollection that one was semi-automatically set one for me when I clicked on the CI failure in the GitHub issue the first time round.

**Comment by andrewkern** [comment]
I'm naive-- what does this orbs thing do for us?

**Comment by grahamgower** [comment]
An orb is a third-party library for circleci (like a wheel for python, but this is for circleci).

I'm fairly certain there's a button for configuring whether actions get triggered in forks, we just need to figure out where the setting is hiding. I looked through the circleci config file and didn't see it, so maybe its in the popsim-consortium github settings, or the popsim-consortium circleci settings?

**Comment by grahamgower** [comment]
I think what happened is that when @hyanwong pushed code to the https://github.com/hyanwong/stdpopsim/tree/patch-2 branch,  the circleci config triggered a circleci build using @hyanwong's circleci account (the default behaviour according to circleci https://circleci.com/docs/2.0/oss/#only-build-pull-requests). Then, because the commit hash for the PR commits are the same as for that fork/branch, circleci didn't rerun the build for the popsim-consortium circleci account (instead, just linking to the existing circleci build).

My bet is that this was happening before the config refactoring in #620, but no one ever noticed because (1) not many PRs come from folks with a circleci account configured, and (2) the build status would have been the same regardless of whos account it the build ran under. Maybe there's also a race going on here, where the fork triggered the circleci build before the PR did? I guess that one "fix" here, is for @hyanwong to toggle the "only build pull requests" setting in his circleci account?

**Comment by grahamgower** [comment]
I've toggled the "Only build pull requests" setting for the stdpopsim project settings in circleci. I don't know if this is sufficient.

**Comment by platipo** [comment]
Hi everyone, I'm joining late the conversation and speaking from my limited CircleCI experience of this month.

I also encontered the problem of triggering the build jobs without the admin permissions and failed both when sending an empyt commit and forcing a branch push; it seems that you have to make a change to trigger the builds.

The behaviour is strange but this was the first CircleCI PR for an organization but I know that you have to opt in to make forked PRs build.

I agree that it is frustrating that you have to create a CircleCI account just to see the build log and results.

**Comment by jeromekelleher** [comment]
I'm puzzled by this behaviour too, there's no reason contributors should need a CircleCI account.

**Comment by petrelharp** [comment]
Well, I just ran a test that ran OK and seemed to not use my own CircleCI account. Maybe it's something funny about your set-up, @hyanwong? Let's see if this hits other people.
