### ISSUE TITLE
documenting how to run`liftOver_comeron2012.py` for the DroMel maps that will be uploaded to AWS

### ISSUE THREAD

**Issue by jradrion** [popsim-consortium/stdpopsim#695]
The following run command will automatically be saved as a part of the `README` file which @andrewkern will be uploading to AWS, along with revised maps for DroMel. All files will be contained within the `comeron2012_maps.tar.gz` tarball. Is there a need or desire to document this somewhere else, in the maintenance section of the documentation perhaps?

```
 python liftOver_comeron2012.py \
    --winLen 1000 \
    --gapThresh 1000000 \
    --useAdjacentAvg \
    --retainIntermediates
```

**Comment by grahamgower** [comment]
Hi @jradrion. I think it's fine to include this info in a README. But it would great to also have this same command given in a comment in the `stdpopsim/DroMel/__init__.py` file above the Comeron genetic map declaration.

> All files will be contained within the `comeron2012_maps.tar.gz` tarball.

Apologies if I misinterpret this, but it sounds like both new and old recombination map files are going to be included in a new tarball, but the new tarball will have the same name as before (`comeron2012_maps.tar.gz`). **Please don't do this**. I recently added SHA256 checksums for all the recombination map files, and stdpopsim now checks each downloaded file against the checksum (#561/#676). This protects users against partially downloaded files, and other potential issues (including those that devs might inadvertantly cause). The SHA256 checksum for a given file can be found in the `sha256` keyword argument where the genetic map is defined (ie. the call to `stdpopsim.GeneticMap()` in the catalog).

**It is important that the existing `comeron2012_maps.tar.gz` file on AWS is not modified.** This file is currently used by the `0.1.2` release of stdpopsim, and this version is likely installed on a lot of computers by now. Changing the tarball has the potential to break old releases. (and once the checksumming stuff is in a released version of stdpopsim, the breakage will be an explicit checsum failure, rather than the possibility of silently doing the wrong thing)

Any new genetic maps should be uploaded in a new tarball, whose name includes the assembly version. Then, the genetic map definition in the catalog should be updated to change the url and the sha256 for the new file.  (See SHA256 bits towards the end of the "adding a genetic map" docs https://stdpopsim.readthedocs.io/en/latest/development.html#adding-a-genetic-map). The url/sha256 update can happen at any time after the file is uploaded. Once complete, both old stdpopsim code and new stdpopsim code will both operate correctly.

The only time an existing tarball on AWS should be modifie, is if there is a genuine problem with the maps in that file. E.g. the PonAbe maps right now cannot be loaded at all (see #595). So once we have fixed maps for PonAbe, they can replace the existing files (and the sha256 fields must be updated in the catalog). Ordinarily, this would (potentially) break old stdpopsim releases, but these are already broken, so users would need to upgrade anyway.

And now that I've written all this, I realise that yes, we probably need a section in the dev docs about the liftover and AWS upload processes.

**Comment by jeromekelleher** [comment]
Thanks @grahamgower, important points. We do need to document this and (at some point) improve our tooling around it.

**Comment by jradrion** [comment]
Thanks, @grahamgower. Sorry, I should have asked about this earlier. I assumed that we would be replacing the existing tarball for DroMel on AWS, which is why I used identical filenames. Also, the new tarball does not contain the original map files, only the updated map files. I just assumed that replacing the files would not break anything for users that already had installed `0.1.2` because I figured that previously cached map files would be used, and if they had not yet been cashed the user would simply download the new files from AWS. Clearly this was a bad assumption. 

I should note that for `liftOver_catalog.py`, the new tarball is not named the same as the old tarball, and does include the assembly name in the tarball filename. I only did it this way for DroMel because I thought having two maps for the same assembly from the same primary source would be confusing.

**Comment by grahamgower** [comment]
Oh, right, this is for DroMel only? Where you're intending to change the current maps (for the same assembly)? I might have been a bit overzealous in my reaction then. :-) Overwriting the file won't break anything in this case. But its probably still not great, because the simulations won't necessarily be reproducible across different installations of stdpopsim v0.1.2.

I think we'll strongly urge users to upgrade for the next release anyway, given how many things we're going to be fixing (e.g. all the species QC stuff).

**Comment by jradrion** [comment]
I can add the above command to`stdpopsim/DroMel/__init__.py`. I'll change the naming of the new tarball to something else, maybe `dm6_comeron2012_v2.tar.gz`? I can then update the catalog with this new map. I'm still a little confused about SHA256 checksum. Is that something that will need to be obtained by the person who actually does the uploading to AWS, or if I obtain a checksum it will be the same as the one obtained by @andrewkern before uploading?

**Comment by jradrion** [comment]
Yes, this was for DroMel only (same assembly, derived from the same source map, just slightly different because I lost the code for how I did it the first time).

> But its probably still not great, because the simulations won't necessarily be reproducible across different installations of stdpopsim v0.1.2.

I agree, this is not ideal. I'm not sure what the best solution is. Getting everyone to upgrade would of course be great.

**Comment by grahamgower** [comment]
The sha256 checksum is a summary of the file that is unique to that file's contents. So if you calculate it on the file that gets uploaded, that should be fine. It's also fine to calculate it after the file has been uploaded---if you change the url in the __init__.py file, without changing the sha256, running the tests should fail with an error that prints both sha256es (if I remember correctly). You can then just include the sha256 from that error message as calculated for the downloaded file. Finally, submit a pr for the changed url and sha256.

**Comment by jradrion** [comment]
OK, sounds good. I will report back if I run into any problems/questions.
