### ISSUE TITLE
Add selfing?

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/stdpopsim#715]
This has come up in two workshops now, and is something we might really have to deal with to add a bunch of other species (e.g. rice). We could at least add a selfing rate for the SLiM engine easily, but I don't know the state-of-the-art for doing it with a coalescent simulator.

Apparently, the latest dadi has a "selfing adjustment"; maybe @RyanGutenkunst knows what we should do here?

**Comment by mufernando** [comment]
There is this msprime issue with some ideas: https://github.com/tskit-dev/msprime/issues/789

**Comment by petrelharp** [comment]
Oh, excellent. There's a bunch of confusing issues here: like, many demographic models were estimated without selfing, i.e., they've already got the selfing baked in.

**Comment by RyanGutenkunst** [comment]
In dadi, our focus on modeling selfing was for recent inbreeding that directly affects the site frequency spectrum (because you’re effectively not randomly sampling chromosomes). For long term inbreeding, we fell back on the typical scaling of the diffusion term (i.e. Ne) by 1+F. @pblischak may have more insight on that.

**Comment by pblischak** [comment]
I think the main issue for a coalescent simulator and selfing is that it can't capture the increase in homozygosity within individuals if chromosomes, rather than individuals, are randomly sampled from the population. Both theta and rho can be scaled by 1+F like Ryan mentioned but the non-random sampling is what may cause the bigger issue. People have typically dealt with this by only sampling one allele per SNP (or some version of this), effectively "haploidizing" their data

**Comment by petrelharp** [comment]
Closing in favor of #857
